"""The seven ciphers under test, shared by every hardware target.

An FPGA number and a Cortex-M4 number must always name the same cipher at the
same round count. Keeping one definition here is what guarantees that; both
tools/gen_fpga.py and tools/run_m4_bench.py import it rather than restating it.
"""

import json
import os
import re

DEFAULT_VARIANTS = [
    "variants/present-80-r16.json",
    "variants/present-80-lin444-297-r7.json",
    "variants/cipher-D.json",
    "variants/cipher-D-lin444-297-r5.json",
    "variants/cipher-D-lin444-297-aes-r5.json",
    "variants/wide/aes.json",
    "variants/wide/aes-lin444-0-8-15.json",
]

# Two variants are benchmarked at a round count their JSON does not declare.
# name in JSON -> (name to report, rounds to run)
VARIANT_OVERRIDES = {
    "aes": ("aes-r5", 5),
    "aes-lin444-0-8-15": ("aes-lin444-0-8-15-r4", 4),
}

# The 128-bit ciphers live in bench/wide_ciphers.h, not src/.
WIDE_VARIANTS = frozenset({"aes", "aes-lin444-0-8-15"})


def _name_of(json_path: str) -> str:
    return json_path.rsplit("/", 1)[-1][: -len(".json")]


def resolve() -> list[tuple[str, str, int]]:
    """Returns (json_path, reported_name, rounds) for each of the seven ciphers.

    Rounds come from VARIANT_OVERRIDES when present, otherwise from the JSON.
    """
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    out = []
    for path in DEFAULT_VARIANTS:
        base = _name_of(path)
        with open(os.path.join(root, path)) as fh:
            declared = json.load(fh)["rounds"]
        name, rounds = VARIANT_OVERRIDES.get(base, (base, declared))
        out.append((path, name, rounds))
    return out


def is_wide(json_path: str) -> bool:
    return _name_of(json_path) in WIDE_VARIANTS


def slug(name: str) -> str:
    """A cipher or variant name as a C identifier and a make variable suffix.

    One rule, used in three places that have to agree character for character:
    tools/gen_c.py's PRESENT_KERNEL_ENC_OF_<slug> (keyed on the *variant* name),
    tools/gen_m4_kats.py's M4_CIPHER_*_<slug> (keyed on the *reported* name), and
    the per-cipher firmware targets in the Makefile. A build selects its cipher by
    passing one slug to all three, so a second spelling of this rule anywhere would
    show up as a link error at best and as a firmware running the wrong kernel at
    worst.
    """
    return re.sub(r"[^0-9A-Za-z]", "_", name)


def family(name: str, json_path: str) -> str:
    """'narrow' (a src/ 64-bit variant), or 'aes'/'lin' for the 128-bit pair.

    The wide pair splits by family because the two have separate kernels in
    bench/wide_ciphers.h, and the firmware instantiates them separately.
    """
    if not is_wide(json_path):
        return "narrow"
    return "lin" if "lin444" in name else "aes"


def make_fragment() -> str:
    """The cipher set as make variables, for the per-cipher firmware images.

    The Makefile needs the list of ciphers at parse time, to define one ELF target
    per (cipher, memory configuration). It cannot import this module, and restating
    seven names in a second file is exactly the drift this module exists to prevent,
    so it reads them from here instead.

    Two variables per cipher, both keyed on the reported name's slug:

      M4_ONE_VARIANT_<slug>   the *variant* slug, or empty for the 128-bit pair.
                              Non-empty means the image can also fix its bitsliced
                              kernel at compile time via -DPRESENT_ONE_CIPHER, which
                              is what lets the linker drop the other fifteen; the
                              128-bit ciphers have no src/ kernel to fix.
      M4_ONE_FAM_<slug>       narrow | aes | lin, for the record and for targets
                              that want to select a family.

    The variant slug is spelled out per cipher rather than derived from the cipher
    slug because the two differ: cipher_set renames two variants when it reports
    them (aes -> aes-r5), and the kernel-id macros in src/gen/lin_consts.h are keyed
    on the name in the variant JSON, not on the reported one.
    """
    lines = [
        "# AUTO-GENERATED by tools/cipher_set.py --make. Do not edit.",
        "# Regenerate with: make fw/m4/gen/ciphers.mk",
        "",
    ]
    slugs = []
    for path, name, _rounds in resolve():
        s = slug(name)
        slugs.append(s)
        variant = "" if is_wide(path) else slug(_name_of(path))
        lines.append(f"M4_ONE_VARIANT_{s} := {variant}")
        lines.append(f"M4_ONE_FAM_{s} := {family(name, path)}")
    lines.insert(3, "M4_ONE_SLUGS := " + " ".join(slugs))
    lines.insert(4, "")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import sys

    if sys.argv[1:] == ["--make"]:
        sys.stdout.write(make_fragment())
    else:
        raise SystemExit(f"usage: {sys.argv[0]} --make")
