#!/usr/bin/env python3
"""Derive retyped S-box circuits from the scalar u64 ones.

The bitslice S-box circuits in src/gen/sbox_circuits.h are pure boolean programs
over `& | ^ ~` -- the exact operator set GCC/Clang support for both vector
extension types and plain scalar integer types. So a derived circuit for an
S-box is just the u64 circuit with its element type retyped: to a 128-bit
two-lane vector `u64x2` for NEON (every gate then compiles to one NEON
instruction -- vand/vorr/veor/vmvn/vbic/vorn -- and the same program encrypts
128 blocks at once instead of 64), or to plain `uint32_t` for a 32-bit scalar
target such as Cortex-M4 (where a `uint64_t` is a register pair and every gate
would otherwise cost two instructions; Thumb-2's BIC and ORN mean the u64 gate
set still maps one gate to one instruction, and 32 blocks are bitsliced at
once instead of 64).

This is a mechanical retype, not a re-synthesis: the u64 circuits are already
minimal (4-bit) or the chosen 8-bit programs, and every target above shares
their gate set, so reusing them keeps each derived path bit-for-bit identical
to the scalar one. Deriving rather than hand-writing also means a derived
header cannot drift from the circuits the rest of the harness verifies.

Usage: tools/gen_retyped_circuits.py <target> [src/gen/sbox_circuits.h] [dst.h]
"""
import sys

# One entry per derived backend. `guard` is None when the header needs no
# target predicate; `typedef` is None when the C type is already spelled.
TARGETS = {
    "neon": {
        "suffix": "_neon_c",
        "ctype": "u64x2",
        "guard": "__ARM_NEON",
        "typedef": ('/* may_alias: the round functions view a uint64_t bitslice buffer through this\n'
                    ' * type, exactly as the AVX2 path views its buffer as __m256i. */\n'
                    'typedef uint64_t u64x2 __attribute__((vector_size(16), may_alias));\n'),
        "blurb": ("The scalar u64 circuits, retyped onto a 128-bit two-lane vector so each gate\n"
                  "is one NEON op and 128 blocks are bitsliced at once. Only compiled on targets\n"
                  "that actually have NEON; elsewhere the header is empty."),
    },
    "u32": {
        "suffix": "_u32_c",
        "ctype": "uint32_t",
        "guard": None,
        "typedef": None,
        "blurb": ("The scalar u64 circuits, retyped onto a 32-bit word: 32 blocks bitsliced at\n"
                  "once instead of 64. This is the path for 32-bit targets (Cortex-M4), where a\n"
                  "uint64_t is a register pair and every gate would otherwise cost two\n"
                  "instructions. Thumb-2 has BIC and ORN, so the u64 gate set still maps one\n"
                  "gate to one instruction."),
    },
}

if len(sys.argv) < 2 or sys.argv[1] not in TARGETS:
    sys.exit(f"usage: {sys.argv[0]} <{'|'.join(TARGETS)}> [src] [dst]")

TARGET = sys.argv[1]
SRC = sys.argv[2] if len(sys.argv) > 2 else "src/gen/sbox_circuits.h"
DST = sys.argv[3] if len(sys.argv) > 3 else f"src/gen/sbox_circuits_{TARGET}.h"

spec = TARGETS[TARGET]

with open(SRC) as f:
    lines = f.readlines()

# The u64 circuit definitions run from the first `present_circuit*_u64_c*` function
# down to the `#if defined(__AVX2__)` that guards the AVX2 copies. Everything in
# that span is scalar circuit code and nothing else.
start = next(i for i, l in enumerate(lines)
             if "static inline void present_circuit" in l and "_u64_c" in l)
end = next(i for i, l in enumerate(lines)
          if i > start and l.strip() == "#if defined(__AVX2__)")

body = []
for l in lines[start:end]:
    l = l.replace("_u64_c", spec["suffix"])   # function names: present_circuit[8]_u64_cN
    l = l.replace("uint64_t", spec["ctype"])  # parameter, local and temporary types
    body.append(l)

guard_name = f"PRESENT_SBOX_CIRCUITS_{TARGET.upper()}_H"

out = [
    "/* AUTO-GENERATED by tools/gen_retyped_circuits.py from src/gen/sbox_circuits.h.\n",
    " * Do not edit. Regenerate with: make generate\n",
    " *\n",
]
blurb_lines = spec["blurb"].split("\n")
out += [f" * {bl}\n" for bl in blurb_lines[:-1]]
out.append(f" * {blurb_lines[-1]} */\n")
out += [
    f"#ifndef {guard_name}\n",
    f"#define {guard_name}\n\n",
    "#include <stdint.h>\n\n",
]
if spec["guard"] is not None:
    out.append(f"#if defined({spec['guard']})\n\n")
if spec["typedef"] is not None:
    out.append(spec["typedef"])
    out.append("\n")
out += body
if spec["guard"] is not None:
    out.append(f"\n#endif /* {spec['guard']} */\n")
out += [
    "\n",
    f"#endif /* {guard_name} */\n",
]

with open(DST, "w") as f:
    f.writelines(out)

n_funcs = sum(1 for l in body if "static inline void present_circuit" in l)
sys.stderr.write(f"gen_retyped_circuits[{TARGET}]: {n_funcs} circuits -> {DST}\n")
