#!/usr/bin/env python3
"""Derive the ARM-NEON S-box circuits from the scalar u64 ones.

The bitslice S-box circuits in src/gen/sbox_circuits.h are pure boolean programs
over `& | ^ ~` -- the exact operator set GCC/Clang vector extensions support on a
`vector_size` type. So the NEON circuit for an S-box is the u64 circuit with its
element type widened from `uint64_t` to a 128-bit two-lane vector `u64x2`; every
gate then compiles to one NEON instruction (vand/vorr/veor/vmvn/vbic/vorn) and the
same program encrypts 128 blocks at once instead of 64.

This is a mechanical retype, not a re-synthesis: the u64 circuits are already
minimal (4-bit) or the chosen 8-bit programs, and NEON shares their gate set, so
reusing them keeps the NEON path bit-for-bit identical to the scalar one. Deriving
rather than hand-writing also means the NEON header cannot drift from the circuits
the rest of the harness verifies.

Usage: tools/gen_neon_circuits.py [src/gen/sbox_circuits.h] [src/gen/sbox_circuits_neon.h]
"""
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "src/gen/sbox_circuits.h"
DST = sys.argv[2] if len(sys.argv) > 2 else "src/gen/sbox_circuits_neon.h"

with open(SRC) as f:
    lines = f.readlines()

# The u64 circuit definitions run from the first `present_circuit*_u64_c*` function
# down to the `#if defined(__AVX2__)` that guards the AVX2 copies. Everything in
# that span is scalar circuit code and nothing else.
start = next(i for i, l in enumerate(lines)
             if "static inline void present_circuit" in l and "_u64_c" in l)
end = next(i for i, l in enumerate(lines)
          if i > start and l.strip() == "#if defined(__AVX2__)")

body = []
for l in lines[start:end]:
    l = l.replace("_u64_c", "_neon_c")   # function names: present_circuit[8]_u64_cN
    l = l.replace("uint64_t", "u64x2")   # parameter, local and temporary types
    body.append(l)

out = [
    "/* AUTO-GENERATED by tools/gen_neon_circuits.py from src/gen/sbox_circuits.h.\n",
    " * Do not edit. Regenerate with: make generate\n",
    " *\n",
    " * The scalar u64 circuits, retyped onto a 128-bit two-lane vector so each gate\n",
    " * is one NEON op and 128 blocks are bitsliced at once. Only compiled on targets\n",
    " * that actually have NEON; elsewhere the header is empty. */\n",
    "#ifndef PRESENT_SBOX_CIRCUITS_NEON_H\n",
    "#define PRESENT_SBOX_CIRCUITS_NEON_H\n\n",
    "#include <stdint.h>\n\n",
    "#if defined(__ARM_NEON)\n\n",
    "/* may_alias: the round functions view a uint64_t bitslice buffer through this\n",
    " * type, exactly as the AVX2 path views its buffer as __m256i. */\n",
    "typedef uint64_t u64x2 __attribute__((vector_size(16), may_alias));\n\n",
]
out += body
out += [
    "\n#endif /* __ARM_NEON */\n\n",
    "#endif /* PRESENT_SBOX_CIRCUITS_NEON_H */\n",
]

with open(DST, "w") as f:
    f.writelines(out)

n_funcs = sum(1 for l in body if "static inline void present_circuit" in l)
sys.stderr.write(f"gen_neon_circuits: {n_funcs} circuits -> {DST}\n")
