#!/usr/bin/env python3
"""Generate the C sources that depend on variants/*.json.

Writes:
  src/gen/variants_gen.c      the variant registry
  src/gen/sbox_circuits.h     synthesised bitslice circuits, one per distinct S-box

The circuit synthesiser (tools/sbox_synth) must already be built; the Makefile
handles that ordering.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "analysis"))

from present_sat import linear as linlib  # noqa: E402
from present_sat import sbox as sboxlib  # noqa: E402
from present_sat.variants import load_all  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import known_circuits  # noqa: E402
import sbox_synth8  # noqa: E402
from cipher_set import slug  # noqa: E402

BANNER = (
    "/* AUTO-GENERATED by tools/gen_c.py from the variants directory. Do not edit.\n"
    " * Regenerate with: make generate\n */\n"
)


BACKENDS = ("u64", "avx2")

# Matches PRESENT_NO_KERNEL: this variant has no bitsliced round function.
NO_KERNEL = -1


def synth(binary: str, table, name: str, backend: str,
          outcomp: int | None = None) -> tuple[str, int, int]:
    """Returns (C code, gate count, output-complement mask) for one S-box.

    ``outcomp`` pins which outputs the circuit is allowed to produce complemented;
    None lets the synthesiser choose. See gen_circuits for why that choice has to
    be made once and then imposed on the second backend.
    """
    args = [binary, ",".join(str(x) for x in table), name, "--backend", backend]
    if outcomp is not None:
        args += ["--outcomp", str(outcomp)]
    res = subprocess.run(args, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"sbox_synth failed for {name}/{backend}: {res.stderr}")
    sys.stderr.write(res.stderr)
    gates, mask, keep = None, None, []
    for line in res.stdout.splitlines():
        if line.startswith("#define PRESENT_CIRCUIT_GATES_"):
            gates = int(line.rsplit(" ", 1)[1])
        elif line.startswith("#define PRESENT_CIRCUIT_OUTCOMP_"):
            mask = int(line.rsplit(" ", 1)[1], 16)
        else:
            keep.append(line)
    if gates is None or mask is None:
        raise RuntimeError(f"sbox_synth emitted no gate count for {name}/{backend}")
    if outcomp is not None and mask != outcomp:
        raise RuntimeError(f"{name}/{backend}: asked for outcomp {outcomp:#x}, got {mask:#x}")
    return "\n".join(keep), gates, mask


def gen_circuits(variants, binary: str, out_path: str) -> dict:
    """Synthesise one circuit per distinct S-box table. Returns table -> circuit id.

    Each S-box is synthesised once per backend. The gate sets differ -- AVX2 has no
    single instruction for ~a|b or ~(a^b) -- so the two circuits are genuinely
    different, not one circuit with the operators textually swapped.

    A circuit is allowed to emit S(x) ^ b for a constant nibble b, because the
    following layer is linear and the resulting L(b) is cancelled by one XOR into
    the next round key at setup time; present_core.c does the folding. That is what
    removes the two NOT gates terminating PRESENT's own AVX2 circuit, 17 -> 15.

    Both backends must agree on b, since they share one set of round keys, and AVX2
    is the one that pays for a NOT -- so AVX2 chooses and u64 is pinned to its
    answer. u64 has XNOR natively, so being pinned costs it nothing (measured: 15
    gates for PRESENT's S-box either way).

    The two widths are synthesised by different tools because the problems are
    different. tools/sbox_synth searches all 65536 truth tables of four variables
    exhaustively, so its 4-bit result is minimal. Eight variables are 2**256
    functions, so tools/sbox_synth8 instead builds a shared BDD over the eight output
    bits and turns each node into a multiplexer -- a heuristic, and the resulting
    circuits are two orders of magnitude larger. Both feed the same circuit table,
    with the width recorded per entry so the kernels know which signature to call.
    """
    tables: list[tuple[int, ...]] = []
    widths: list[int] = []
    index: dict[tuple[int, ...], int] = {}

    def intern(tbl, bits) -> int:
        key = tuple(tbl)
        if key not in index:
            index[key] = len(tables)
            tables.append(key)
            widths.append(bits)
        return index[key]

    for v in variants:
        intern(v.sbox, v.sbox_bits)
        intern(v.sbox_inv, v.sbox_bits)

    parts = [BANNER, "#ifndef PRESENT_SBOX_CIRCUITS_H\n#define PRESENT_SBOX_CIRCUITS_H\n\n",
             "#include <stdint.h>\n\n",
             "#if defined(__AVX2__)\n#include <immintrin.h>\n#endif\n\n"]
    counts: dict[str, list[int]] = {b: [] for b in BACKENDS}
    codes: dict[str, list[str]] = {b: [] for b in BACKENDS}
    outcomp: list[int] = []

    for cid, (tbl, bits) in enumerate(zip(tables, widths)):
        if bits == 8:
            # A published circuit wins when there is one: it can use the S-box's
            # algebra, where the BDD only ever sees 256 table entries. Both paths
            # are verified against the table below, so the two are interchangeable
            # as far as correctness goes -- only the gate count differs.
            known = known_circuits.lookup(tbl)
            if known is not None:
                ops, outs, kname = known
                per_backend = [(ops, outs)] * len(BACKENDS)
                note = f"published {kname} circuit"
            else:
                # No output-complement search here: the mask exists to delete NOT
                # gates terminating the circuit, and against 1100 gates the couple
                # it might save is not worth another 8! pass.
                best = sbox_synth8.synth(list(tbl))
                per_backend = [(best[b][2], best[b][3]) for b in BACKENDS]
                note = "BDD synthesis"
            outcomp.append(0)
            for backend, (ops, outs) in zip(BACKENDS, per_backend):
                sbox_synth8.verify(list(tbl), ops, outs, None)
                codes[backend].append(sbox_synth8.render_c(f"c{cid}", ops, outs, backend))
                counts[backend].append(sbox_synth8.cost(ops, backend))
            sys.stderr.write(f"circuit c{cid}: 8-bit, {note}, "
                             + ", ".join(f"{b} {counts[b][-1]} gates" for b in BACKENDS)
                             + "\n")
            continue
        code, gates, mask = synth(binary, list(tbl), f"c{cid}", "avx2")
        codes["avx2"].append(code)
        counts["avx2"].append(gates)
        outcomp.append(mask)
        code, gates, _ = synth(binary, list(tbl), f"c{cid}", "u64", outcomp=mask)
        codes["u64"].append(code)
        counts["u64"].append(gates)

    for backend in BACKENDS:
        if backend == "avx2":
            parts.append("#if defined(__AVX2__)\n\n")
        parts.extend(c + "\n\n" for c in codes[backend])
        if backend == "avx2":
            parts.append("#endif /* __AVX2__ */\n\n")

    parts.append(f"#define PRESENT_N_CIRCUITS {len(tables)}\n\n")
    parts.append("#define PRESENT_CIRCUIT_LIST(X) \\\n")
    parts.append("    " + " \\\n    ".join(f"X({i})" for i in range(len(tables))) + "\n\n")
    for backend in BACKENDS:
        parts.append(f"static const int present_circuit_gates_{backend}[PRESENT_N_CIRCUITS] = {{\n")
        parts.append("    " + ", ".join(str(g) for g in counts[backend]) + "\n};\n\n")
    parts.append("/* S-box width of each circuit: 4 means present_circuit_<backend>_cN,\n"
                 " * 8 means present_circuit8_<backend>_cN. The two have different arities,\n"
                 " * so the kernel that calls one is specialised on this. */\n")
    parts.append("static const int present_circuit_sbox_bits[PRESENT_N_CIRCUITS] = {\n")
    parts.append("    " + ", ".join(str(w) for w in widths) + "\n};\n\n")
    parts.append(
        "/* Circuit i computes S(x) ^ present_circuit_outcomp[i], nibble-wise: bit j set\n"
        " * means output bit j comes out complemented. Both backends share the mask.\n"
        " * present_core.c cancels it in the round keys, so callers see plain S. */\n")
    parts.append("static const int present_circuit_outcomp[PRESENT_N_CIRCUITS] = {\n")
    parts.append("    " + ", ".join(f"0x{m:x}" for m in outcomp) + "\n};\n\n")
    parts.append("#endif /* PRESENT_SBOX_CIRCUITS_H */\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return index


def layer_of(v) -> tuple[str, str]:
    """The variant's linear layer as (kind token, tag), both usable in C identifiers."""
    if v.linear is not None:
        c = tuple(int(x) for x in v.linear["c0"])
        # The layer body is identical at either width -- it is 64 bits of XOR either
        # way -- but the round function around it differs, because the S-box loop runs
        # over 8 circuits of 8 words instead of 16 of 4.
        kind = "LIN4448" if v.sbox_bits == 8 else "LIN444"
        return kind, f"{c[0]}_{c[1]}_{c[2]}"
    # PBOX8 is the same permutation as PBOX, but fused into an 8-wide S-box store
    # rather than a 4-wide one, so it needs its own X-macro list and round function.
    return ("PBOX8" if v.sbox_bits == 8 else "PBOX"), None  # tag filled in by plan_layers


def plan_layers(variants, circuit_index: dict):
    """Work out what the bitsliced backends have to instantiate.

    Both of them specialise on the linear layer as well as on the S-box: an index
    read from the variant descriptor costs scalar address arithmetic per operand,
    and at 64 stores a round that is the same order of magnitude as the vector work
    it addresses. So a *kernel* is a (circuit, layer) pair with both fixed at
    compile time.

    Instantiating the full cross product would be silly -- 10 circuits against 8
    layers of straight-line code, when no variant uses most of the pairs. Only the
    pairs some variant actually asks for are emitted, which comes to fewer
    functions than the circuit x {pbox, lin444} split this replaces.

    A variant whose S-box has no synthesised circuit gets no kernel either, and
    contributes nothing to the layer tables -- there would be no round function to
    instantiate them for.

    Returns (pboxes, layers, enc_kernels, dec_kernels, ids) where ids[i] is the
    (encryption, decryption) kernel index of variants[i]. `pboxes` entries are
    (table, widths) -- the permutation plus the set of S-box widths that fuse a store
    into it, since a 4-bit and an 8-bit variant can share a permutation but not the
    store macro.
    """
    pboxes: list[tuple] = []
    pbox_widths: list[set] = []
    layers: list[tuple[str, str] | None] = []
    for v in variants:
        if tuple(v.sbox) not in circuit_index:
            layers.append(None)
            continue
        kind, tag = layer_of(v)
        if kind in ("PBOX", "PBOX8"):
            key = tuple(v.pbox)
            if key not in pboxes:
                pboxes.append(key)
                pbox_widths.append(set())
            tag = f"p{pboxes.index(key)}"
            pbox_widths[pboxes.index(key)].add(v.sbox_bits)
        layers.append((kind, tag))

    enc_kernels: list[tuple] = []
    dec_kernels: list[tuple] = []
    ids = []
    for v, layer in zip(variants, layers):
        if layer is None:
            ids.append((NO_KERNEL, NO_KERNEL))
            continue
        kind, tag = layer
        e = (circuit_index[tuple(v.sbox)], kind, tag)
        d = (circuit_index[tuple(v.sbox_inv)], kind, tag)
        if e not in enc_kernels:
            enc_kernels.append(e)
        if d not in dec_kernels:
            dec_kernels.append(d)
        ids.append((enc_kernels.index(e), dec_kernels.index(d)))
    return list(zip(pboxes, pbox_widths)), layers, enc_kernels, dec_kernels, ids


def _pbox_macros(pboxes) -> list[str]:
    """Per-permutation X-macro lists: where each state bit goes, as literals."""
    out = []
    for idx, (pb, bits_used) in enumerate(pboxes):
        tag = f"p{idx}"
        inv = [0] * 64
        for i, d in enumerate(pb):
            inv[d] = i
        out.append(
            f"\n/* Permutation {tag}. STORE groups the destinations by S-box, so the\n"
            " * encryption path can write each circuit's outputs straight to their\n"
            " * permuted slots and the layer costs not even a move. A is passed through\n"
            " * to the callback, which needs the circuit id the X-macro cannot know.\n"
            " * The suffix-free name is the 4-bit grouping; STORE8 is the 8-bit one. */\n")
        for n in sorted(bits_used):
            name = "PRESENT_PBOX_STORE" + ("8" if n == 8 else "")
            args = ", ".join("%d" for _ in range(n))
            out.append(f"#define {name}_{tag}(X, A) \\\n")
            out.append(" \\\n".join(
                ("    X(A, %d, " + args + ")")
                % ((i,) + tuple(pb[n * i + j] for j in range(n)))
                for i in range(64 // n)) + "\n\n")
        out.append("/* X(dst, src) for the inverse, which decryption applies before the\n"
                   " * S-box and so cannot fuse into a store. */\n")
        out.append(f"#define PRESENT_PBOX_MOVEINV_{tag}(X) \\\n")
        out.append(" \\\n".join(
            "    X(%d, %d)" % (inv[i], i) for i in range(64)) + "\n\n")
    return out


def _kernel_macro(name: str, kernels) -> str:
    body = " \\\n".join(f"    X({kid}, {cid}, {kind}, {tag})"
                        for kid, (cid, kind, tag) in enumerate(kernels))
    return f"#define {name}(X) \\\n{body}\n\n"


def gen_lin_consts(triples, costs, pboxes, enc_kernels, dec_kernels, variants,
                   kernel_ids, out_path: str) -> int:
    """Emit the distinct lin444 rotation triples as an X-macro list.

    The bitsliced layers index registers as ``BS(w, k - c)``. With c read from the
    variant descriptor at run time that index is three scalar instructions per
    operand, and the layer ends up issuing more address arithmetic than vector
    work. Specialising on the constants makes every index an immediate, which is
    the same trick the S-box circuits already use -- hence the same X-macro shape.

    The permutation layers get the same treatment here, for the same reason and to
    keep the comparison between them honest: ``alt[v->pbox[4 * i + j]] = y`` is a
    load and an indexed store, and pricing PRESENT's pLayer that way against a
    lin444 whose rotations *are* immediates would flatter lin444 by 7%.
    """
    parts = [BANNER, "#ifndef PRESENT_LIN_CONSTS_H\n#define PRESENT_LIN_CONSTS_H\n\n"]
    parts.append(f"#define PRESENT_N_LIN444 {len(triples)}\n\n")
    parts.append("/* X(tag, c0, c1, c2) for every rotation triple any variant uses. */\n")
    parts.append("#define PRESENT_LIN444_LIST(X) \\\n")
    if triples:
        parts.append("    " + " \\\n    ".join(
            f"X({a}_{b}_{c}, {a}, {b}, {c})" for a, b, c in triples) + "\n")
    parts.append("""
/* Bitsliced XOR count per round. Three independent conditions each let one pair
 * of operands be shared between two of the four output words; they coincide only
 * in the geometric family c = (a,2a,3a). The decryption conditions are the mirror
 * image because the inverse recovers the last word first. Kept in step with
 * analysis/present_sat/slp.py by tests/test_variants. */
static inline int present_lin444_xors(const int c[3], int decrypt)
{
    const int W = PRESENT_LIN444_WORD_BITS;
    int a = c[0] & (W - 1), b = c[1] & (W - 1), z = c[2] & (W - 1);
    if (decrypt) {
        if (a == ((b + z) & (W - 1))) return 9 * W;
        if (b == ((2 * z) & (W - 1))) return 10 * W;
    } else {
        if (z == ((a + b) & (W - 1))) return 9 * W;
        if (b == ((2 * a) & (W - 1))) return 10 * W;
    }
    if (((z - b) & (W - 1)) == ((b - a) & (W - 1))) return 10 * W;
    return 12 * W;
}
""")
    parts.append(
        "/* X(c0, c1, c2, encryption XORs per round, decryption XORs per round) as\n"
        " * counted by analysis/present_sat/slp.py -- the same enumeration that emitted\n"
        " * the layer bodies. present_lin444_xors() above is the closed form of the same\n"
        " * thing; tests/test_variants checks the two against each other. */\n")
    parts.append("#define PRESENT_LIN444_COST_LIST(X) \\\n")
    if triples:
        parts.append(" \\\n".join(
            f"    X({a}, {b}, {c}, {costs[(a, b, c)][0]}, {costs[(a, b, c)][1]})"
            for a, b, c in triples) + "\n")
    parts.append("\n")
    parts.extend(_pbox_macros(pboxes))
    parts.append("/* X(kernel id, circuit id, layer kind, layer tag). A kernel is one\n"
                 " * bitsliced round function with both halves fixed at compile time; the\n"
                 " * variant descriptor names the one it wants in .kernel_enc/.kernel_dec. */\n")
    parts.append(_kernel_macro("PRESENT_KERNEL_ENC_LIST", enc_kernels))
    parts.append(_kernel_macro("PRESENT_KERNEL_DEC_LIST", dec_kernels))

    # Which kernel each variant wants, as a macro keyed on the variant name with
    # every character that cannot appear in a C identifier replaced by '_'.
    #
    # The registry in variants_gen.c already carries this, in .kernel_enc, and that
    # is the right answer for any build that chooses its cipher at run time. It is
    # the wrong answer for one that chooses at compile time: a value read from a
    # descriptor keeps the dispatch a switch, the switch references all sixteen
    # kernels, and --gc-sections must keep all sixteen -- 71 KB of bitsliced round
    # functions of which a single-cipher firmware executes one. These macros let
    # such a build name its kernel as a constant, so the linker can drop the rest.
    #
    # Emitted for every variant, not just the benchmarked ones: the cost is one
    # #define each, and restricting it to a subset would put a second copy of
    # "which ciphers matter" in the generator.
    parts.append(
        "/* PRESENT_KERNEL_ENC_OF_<slug> -- the encryption kernel id for one variant,\n"
        " * as a compile-time constant. <slug> is the variant name with '-' and '.'\n"
        " * replaced by '_'. Exists so a firmware built for a single cipher can call\n"
        " * bs32_enc_k<id> directly instead of switching on ctx->var->kernel_enc; the\n"
        " * switch is what forces every kernel to be linked. See PRESENT_ONE_CIPHER in\n"
        " * src/present_bitslice32.c. */\n")
    for v, (kern_enc, _kern_dec) in zip(variants, kernel_ids):
        parts.append(f"#define PRESENT_KERNEL_ENC_OF_{slug(v.name)} {kern_enc}\n")
    parts.append("\n#endif /* PRESENT_LIN_CONSTS_H */\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return len(triples)


def _c_term(atom, rot: int) -> str:
    """One operand of an XOR, as a bitsliced register index.

    Word w bit k is register w * WB + k, so ROTL(x, r) read at output bit k is x
    read at bit k - r. That is why the rotations cost nothing here -- provided the
    constant is a literal, which is the whole point of specialising.
    """
    kind, where = atom
    idx = "k" if rot == 0 else f"k - {rot}"
    if kind == "tmp":
        return f"{where}[TS({idx})]"
    return f"{kind}[BS({where}, {idx})]"


def _c_xor(terms) -> str:
    """Balanced XOR tree over the terms, so the chain is depth 2 rather than 3."""
    exprs = [_c_term(a, r) for a, r in terms]
    while len(exprs) > 1:
        nxt = [f"XOR({exprs[i]}, {exprs[i + 1]})" for i in range(0, len(exprs) - 1, 2)]
        if len(exprs) % 2:
            nxt.append(exprs[-1])
        exprs = nxt
    return exprs[0]


def _c_lin444_body(name: str, prog) -> str:
    """One IR program as a macro body taking (T, XOR, in, out)."""
    temps = [t[1] for t, _ in prog if t[0] == "tmp"]
    stmts = []
    if temps:
        stmts.append("T " + ", ".join(f"{n}[WB]" for n in temps) + ";")
    for target, terms in prog:
        # A loop must never read the array it is writing: each line's target is a
        # word the line does not read, which is exactly what makes lin444
        # unitriangular. Assert it rather than assume it.
        assert target not in [a for a, _ in terms], f"{name}: statement reads its own target"
        kind, where = target
        lhs = f"{where}[k]" if kind == "tmp" else f"out[BS({where}, k)]"
        stmts.append(f"for (int k = 0; k < WB; k++) {lhs} = {_c_xor(terms)};")
    body = " \\\n    ".join(stmts)
    return f"#define {name}(T, XOR, in, out) \\\n    {body}\n"


# How many shared temporaries a generated body may introduce. Uncapped: the cap
# exists so the trade can be measured, and it was -- capping does not pay.
#
# Fewer XORs is not the same as less work. The bitsliced state already exceeds the
# register file, so a shared temporary cannot stay in registers: it removes WB
# XORs and adds WB stores, and on AVX2 stores issue on two ports against three for
# the XORs. Measured, per round, for the four triples this project ships:
#
#   c0          form  XORs  instructions  stores  cyc/B
#   (2,9,7)     gen    192           391      97   3.02
#   (0,1,3)     gen    192           395      98   3.01
#   (1,15,13)   ap     160           334      98   2.88
#   (2,1,3)     sum    144           341     116   2.97
#   (2,1,3)     capped 160           355     113   2.97
#
# So the XOR count does not order these; the instruction count does, and the two
# disagree. (1,15,13) wins because the progression form's two temporaries are
# independent -- one serves o0,o1 and the other o2,o3 -- while (2,1,3)'s three are
# a chain, each feeding the next, which lengthens live ranges and spills more.
# Capping (2,1,3) at two temporaries picks two links of that chain and is worse
# still. Left uncapped because that is both the simplest rule and the better one.
LIN444_MAX_TEMPS = 99


def gen_lin444_bodies(triples, out_path: str, max_temps: int = LIN444_MAX_TEMPS) -> dict:
    """Emit a specialised body per rotation triple, in both directions.

    The programs come from analysis/present_sat/slp.py, which enumerates the
    shared subexpressions instead of pattern-matching a few families, and checks
    every program against the definition of the layer on all 64 basis vectors
    before it is emitted. Generating the C from the same object that computes the
    cost is what keeps the two from drifting: there is no second derivation to get
    wrong.
    """
    from present_sat import slp  # noqa: E402

    parts = [BANNER, "#ifndef PRESENT_LIN444_BODIES_H\n#define PRESENT_LIN444_BODIES_H\n\n",
             "/* Include after present/lin444_body.h, which defines WB, BS and TS.\n"
             " * Each body is a macro so a backend can instantiate it with its own word\n"
             " * type and XOR spelling, and so the rotations stay literals. */\n\n"]
    costs = {}
    for a, b, c in triples:
        tag = f"{a}_{b}_{c}"
        (fwd, n_fwd), (inv, n_inv) = slp.programs([a, b, c], max_temps=max_temps)
        costs[(a, b, c)] = (n_fwd, n_inv)
        uncapped = slp.cost([a, b, c])
        note = "" if n_fwd == uncapped else f", {uncapped} available but needs 3 temporaries"
        parts.append(f"/* c0 = ({a},{b},{c}): encryption {n_fwd} XORs/round"
                     f" ({slp.form([a, b, c])}{note}), decryption {n_inv}"
                     f" ({slp.inv_form([a, b, c])}) */\n")
        parts.append(_c_lin444_body(f"LIN444_FWD_BODY_{tag}", fwd))
        parts.append(_c_lin444_body(f"LIN444_INV_BODY_{tag}", inv))
        parts.append("\n")
    parts.append("#endif /* PRESENT_LIN444_BODIES_H */\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return costs


def c_array(values, per_line=16) -> str:
    out = []
    for i in range(0, len(values), per_line):
        out.append(", ".join(str(v) for v in values[i:i + per_line]))
    return ",\n            ".join(out)


def c_u64_array(values, per_line=4) -> str:
    out = []
    for i in range(0, len(values), per_line):
        out.append(", ".join(f"UINT64_C(0x{v:016X})" for v in values[i:i + per_line]))
    return ",\n            ".join(out)


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


KS_ENUM = {
    "present80": "PRESENT_KS_80",
    "present128": "PRESENT_KS_128",
    "independent": "PRESENT_KS_INDEPENDENT",
}


def gen_registry(variants, circuit_index: dict, kernel_ids, out_path: str) -> None:
    parts = [BANNER, '#include "present/variant.h"\n\n']

    # PRESENT_ONE_CIPHER, the single-cipher build (src/internal.h), narrows the
    # registry to its one variant. It is 43 KiB of tables in the full tree -- more
    # than half the code of a per-cipher Cortex-M4 image before this, and every byte
    # of it describing ciphers that image cannot run -- so leaving it whole would
    # make the per-cipher footprint figure as unrepresentative as the combined one.
    #
    # The selection has to happen in #if, and #if cannot compare identifiers, so each
    # variant is given a number and the comparison is numeric. The numbers start at 1
    # so that an unknown slug -- PRESENT_ONE_CIPHER naming something that is not a
    # variant in this tree, e.g. one of the 128-bit ciphers, which live in
    # bench/wide_ciphers.h and have no descriptor here -- expands to 0, keeps nothing,
    # and trips the assertion below rather than silently keeping variant 0.
    parts.append("/* One number per variant, for the PRESENT_ONE_CIPHER selection below. */\n")
    for i, v in enumerate(variants):
        parts.append(f"#define PRESENT_VARIANT_IDX_{slug(v.name)} {i + 1}\n")
    parts.append("""
#ifdef PRESENT_ONE_CIPHER
#define PRESENT_VAR_CAT_(a, b) a##b
#define PRESENT_VAR_CAT(a, b) PRESENT_VAR_CAT_(a, b)
#define PRESENT_VARIANT_KEEP(i) ((i) == PRESENT_VAR_CAT(PRESENT_VARIANT_IDX_, PRESENT_ONE_CIPHER))
#else
#define PRESENT_VARIANT_KEEP(i) 1
#endif

""")
    parts.append("const present_variant_t present_variants[] = {\n")
    for v, (kern_enc, kern_dec) in zip(variants, kernel_ids):
        ks = KS_ENUM[v.key_schedule]
        # A variant with a general linear layer has no pbox; emit the identity so
        # the field is never garbage, and set lin_kind so nothing reads it.
        pbox = v.pbox if v.pbox is not None else list(range(64))
        pbox_inv = v.pbox_inv if v.pbox is not None else list(range(64))
        if v.linear is None:
            lin_kind, c0 = "PRESENT_LIN_PBOX", [0, 0, 0]
        else:
            lin_kind, c0 = "PRESENT_LIN_444", [int(x) for x in v.linear["c0"]]
        parts.append(f"#if PRESENT_VARIANT_KEEP(PRESENT_VARIANT_IDX_{slug(v.name)})\n")
        parts.append("    {\n")
        parts.append(f"        .name = {c_string(v.name)},\n")
        parts.append(f"        .description = {c_string(v.description)},\n")
        parts.append(f"        .sbox_bits = {v.sbox_bits},\n")
        parts.append(f"        .n_sboxes = {v.n_sboxes},\n")
        parts.append(f"        .sbox = {{\n            {c_array(v.sbox)}\n        }},\n")
        parts.append(f"        .sbox_inv = {{\n            {c_array(v.sbox_inv)}\n        }},\n")
        parts.append(f"        .pbox = {{\n            {c_array(pbox)}\n        }},\n")
        parts.append(f"        .pbox_inv = {{\n            {c_array(pbox_inv)}\n        }},\n")
        parts.append(f"        .lin_kind = {lin_kind},\n")
        parts.append(f"        .lin_c0 = {{ {', '.join(str(x) for x in c0)} }},\n")
        parts.append(f"        .lin_col = {{\n            {c_u64_array(v.lin_cols)}\n        }},\n")
        parts.append(f"        .lin_col_inv = {{\n            {c_u64_array(v.lin_cols_inv)}\n        }},\n")
        parts.append(f"        .rounds = {v.rounds},\n")
        parts.append(f"        .key_bits = {v.key_bits},\n")
        parts.append(f"        .key_schedule = {ks},\n")
        parts.append(f"        .circuit_enc = {circuit_index.get(tuple(v.sbox), NO_KERNEL)},\n")
        parts.append(f"        .circuit_dec = {circuit_index.get(tuple(v.sbox_inv), NO_KERNEL)},\n")
        parts.append(f"        .kernel_enc = {kern_enc},\n")
        parts.append(f"        .kernel_dec = {kern_dec},\n")
        parts.append("    },\n")
        parts.append("#endif\n")
    parts.append("};\n\n")
    # Counted rather than stated, because how many entries survive the selection
    # above is not something this generator knows. The divisor is a type size, not
    # present_variants[0], so an empty registry reaches the assertion instead of
    # dividing by zero first.
    parts.append("_Static_assert(sizeof present_variants > 0,\n"
                 "               \"PRESENT_ONE_CIPHER names no variant in this registry\");\n\n")
    parts.append("const int present_n_variants =\n"
                 "    (int)(sizeof present_variants / sizeof(present_variant_t));\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--synth", default=os.path.join(ROOT, "build", "sbox_synth"))
    args = ap.parse_args()

    variants = load_all()
    for v in variants:
        v.validate()
        # A wrong inverse would silently break decryption; check it here, once.
        assert sboxlib.inverse(v.sbox_inv) == v.sbox
        if v.pbox is not None:
            assert sboxlib.inverse(v.pbox_inv) == v.pbox
        # Holds for both kinds: the column form and its inverse compose to identity.
        cols, cols_inv = v.lin_cols, v.lin_cols_inv
        for i in range(64):
            assert linlib.apply_columns(cols_inv, cols[i]) == 1 << i, \
                f"{v.name}: linear layer inverse is wrong at bit {i}"

    triples = sorted({tuple(int(x) for x in v.linear["c0"])
                      for v in variants if v.linear is not None})

    index = gen_circuits(variants, args.synth, os.path.join(ROOT, "src", "gen", "sbox_circuits.h"))
    pboxes, _layers, enc_kernels, dec_kernels, kernel_ids = plan_layers(variants, index)
    gen_registry(variants, index, kernel_ids, os.path.join(ROOT, "src", "gen", "variants_gen.c"))
    costs = gen_lin444_bodies(triples, os.path.join(ROOT, "src", "gen", "lin444_bodies.h"))
    n_lin = gen_lin_consts(triples, costs, pboxes, enc_kernels, dec_kernels,
                           variants, kernel_ids,
                           os.path.join(ROOT, "src", "gen", "lin_consts.h"))
    print(f"generated {len(variants)} variants, {len(index)} distinct S-box circuits, "
          f"{n_lin} lin444 rotation triples, {len(pboxes)} permutations, "
          f"{len(enc_kernels)}+{len(dec_kernels)} bitsliced kernels")
    for c0 in triples:
        enc, dec = costs[c0]
        print(f"  lin444 c0={c0}: {enc} XORs/round encrypt, {dec} decrypt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
