#!/usr/bin/env python3
"""Generate the C sources that depend on variants/*.json.

Writes:
  src/gen/variants_gen.c      the variant registry
  src/gen/sbox_circuits.h     synthesised bitslice circuits, one per distinct S-box

The circuit synthesiser (tools/sbox_synth) must already be built; the Makefile
handles that ordering.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "analysis"))

from present_sat import sbox as sboxlib  # noqa: E402
from present_sat.variants import load_all  # noqa: E402

BANNER = (
    "/* AUTO-GENERATED by tools/gen_c.py from the variants directory. Do not edit.\n"
    " * Regenerate with: make generate\n */\n"
)


def synth(binary: str, table, name: str) -> str:
    args = [binary, ",".join(str(x) for x in table), name]
    res = subprocess.run(args, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"sbox_synth failed for {name}: {res.stderr}")
    sys.stderr.write(res.stderr)
    return res.stdout


def gen_circuits(variants, binary: str, out_path: str) -> dict:
    """Synthesise one circuit per distinct S-box table. Returns table -> circuit id."""
    tables: list[tuple[int, ...]] = []
    index: dict[tuple[int, ...], int] = {}

    def intern(tbl) -> int:
        key = tuple(tbl)
        if key not in index:
            index[key] = len(tables)
            tables.append(key)
        return index[key]

    for v in variants:
        intern(v.sbox)
        intern(v.sbox_inv)

    parts = [BANNER, "#ifndef PRESENT_SBOX_CIRCUITS_H\n#define PRESENT_SBOX_CIRCUITS_H\n\n",
             "#include <stdint.h>\n\n"]
    gate_counts = []
    for cid, tbl in enumerate(tables):
        code = synth(binary, list(tbl), f"c{cid}")
        gates = None
        keep = []
        for line in code.splitlines():
            if line.startswith("#define PRESENT_CIRCUIT_GATES_"):
                gates = int(line.rsplit(" ", 1)[1])
            else:
                keep.append(line)
        gate_counts.append(gates)
        parts.append("\n".join(keep) + "\n\n")

    parts.append(f"#define PRESENT_N_CIRCUITS {len(tables)}\n\n")
    parts.append("#define PRESENT_CIRCUIT_LIST(X) \\\n")
    parts.append("    " + " \\\n    ".join(f"X({i})" for i in range(len(tables))) + "\n\n")
    parts.append("static const int present_circuit_gate_counts[PRESENT_N_CIRCUITS] = {\n")
    parts.append("    " + ", ".join(str(g) for g in gate_counts) + "\n};\n\n")
    parts.append("#endif /* PRESENT_SBOX_CIRCUITS_H */\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return index


def c_array(values, per_line=16) -> str:
    out = []
    for i in range(0, len(values), per_line):
        out.append(", ".join(str(v) for v in values[i:i + per_line]))
    return ",\n            ".join(out)


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_registry(variants, circuit_index: dict, out_path: str) -> None:
    parts = [BANNER, '#include "present/variant.h"\n\n']
    parts.append(f"const present_variant_t present_variants[{len(variants)}] = {{\n")
    for v in variants:
        ks = "PRESENT_KS_80" if v.key_schedule == "present80" else "PRESENT_KS_128"
        parts.append("    {\n")
        parts.append(f"        .name = {c_string(v.name)},\n")
        parts.append(f"        .description = {c_string(v.description)},\n")
        parts.append(f"        .sbox = {{ {c_array(v.sbox)} }},\n")
        parts.append(f"        .sbox_inv = {{ {c_array(v.sbox_inv)} }},\n")
        parts.append(f"        .pbox = {{\n            {c_array(v.pbox)}\n        }},\n")
        parts.append(f"        .pbox_inv = {{\n            {c_array(v.pbox_inv)}\n        }},\n")
        parts.append(f"        .rounds = {v.rounds},\n")
        parts.append(f"        .key_bits = {v.key_bits},\n")
        parts.append(f"        .key_schedule = {ks},\n")
        parts.append(f"        .circuit_enc = {circuit_index[tuple(v.sbox)]},\n")
        parts.append(f"        .circuit_dec = {circuit_index[tuple(v.sbox_inv)]},\n")
        parts.append("    },\n")
    parts.append("};\n\n")
    parts.append(f"const int present_n_variants = {len(variants)};\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--synth", default=os.path.join(ROOT, "build", "sbox_synth"))
    args = ap.parse_args()

    variants = load_all()
    for v in variants:
        v.validate()
        # A wrong inverse would silently break decryption; check it here, once.
        assert sboxlib.inverse(v.sbox_inv) == v.sbox
        assert sboxlib.inverse(v.pbox_inv) == v.pbox

    index = gen_circuits(variants, args.synth, os.path.join(ROOT, "src", "gen", "sbox_circuits.h"))
    gen_registry(variants, index, os.path.join(ROOT, "src", "gen", "variants_gen.c"))
    print(f"generated {len(variants)} variants, {len(index)} distinct S-box circuits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
